# Data Preprocessing 
ML - Project 0

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('property_data.csv')
data

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [4]:
data.head(1)

PID  ST_NUM ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0  PUTNAM            Y            3        1  1000

In [5]:
data.tail(1)

PID  ST_NUM  ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
8  100009000.0   215.0  TREMONT            Y           na        2  1800

In [6]:
data.dtypes

PID             float64
ST_NUM          float64
ST_NAME          object
OWN_OCCUPIED     object
NUM_BEDROOMS     object
NUM_BATH         object
SQ_FT            object
dtype: object

In [7]:
dropped_data = data.dropna()
dropped_data

PID  ST_NUM    ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y            3        1  1000
1  100002000.0   197.0  LEXINGTON            N            3      1.5    --
8  100009000.0   215.0    TREMONT            Y           na        2  1800

In [10]:
dropped_data = data.dropna(axis=1) 
dropped_data

ST_NAME
0      PUTNAM
1   LEXINGTON
2   LEXINGTON
3    BERKELEY
4    BERKELEY
5    BERKELEY
6  WASHINGTON
7     TREMONT
8     TREMONT

In [11]:
dropped_data = data.dropna(how='all')
dropped_data

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [16]:
dropped_data = data.dropna(thresh=int(data.shape[0] * .9), axis=1)
dropped_data

PID     ST_NAME OWN_OCCUPIED NUM_BATH SQ_FT
0  100001000.0      PUTNAM            Y        1  1000
1  100002000.0   LEXINGTON            N      1.5    --
2  100003000.0   LEXINGTON            N        1   850
3  100004000.0    BERKELEY           12      NaN   700
4          NaN    BERKELEY            Y        2  1600
5  100006000.0    BERKELEY            Y        1   800
6  100007000.0  WASHINGTON          NaN   HURLEY   950
7  100008000.0     TREMONT            Y        1   NaN
8  100009000.0     TREMONT            Y        2  1800

In [17]:
dropped_data = data.dropna(thresh=int(data.shape[1] * .9), axis=0)
dropped_data

PID  ST_NUM    ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y            3        1  1000
1  100002000.0   197.0  LEXINGTON            N            3      1.5    --
3  100004000.0   201.0   BERKELEY           12            1      NaN   700
4          NaN   203.0   BERKELEY            Y            3        2  1600
5  100006000.0   207.0   BERKELEY            Y          NaN        1   800
7  100008000.0   213.0    TREMONT            Y            1        1   NaN
8  100009000.0   215.0    TREMONT            Y           na        2  1800

In [18]:
data['ST_NUM'].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
Name: ST_NUM, dtype: bool

In [20]:
data['ST_NUM'].isnull().sum()

2

In [19]:
data['ST_NAME'].isnull().sum()

0

In [23]:
data['ST_NAME'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: ST_NAME, dtype: bool

In [21]:
data.columns

Index(['PID', 'ST_NUM', 'ST_NAME', 'OWN_OCCUPIED', 'NUM_BEDROOMS', 'NUM_BATH',
       'SQ_FT'],
      dtype='object')

In [24]:
np.array(data['ST_NAME'].isnull())

array([False, False, False, False, False, False, False, False, False])

In [26]:
column_names = data.columns
Nan_columns = list()

for col in column_names:
    if(True in np.array(data[col].isnull())):
        Nan_columns.append(col)
        
Nan_columns

['PID', 'ST_NUM', 'OWN_OCCUPIED', 'NUM_BEDROOMS', 'NUM_BATH', 'SQ_FT']

In [27]:
data['SQ_FT'] = data['SQ_FT'].fillna(800)
data

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   800
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [28]:
data['ST_NUM'] = data['ST_NUM'].fillna(data['ST_NUM'].mean())
data

PID      ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH  \
0  100001000.0  104.000000      PUTNAM            Y            3        1   
1  100002000.0  197.000000   LEXINGTON            N            3      1.5   
2  100003000.0  191.428571   LEXINGTON            N          NaN        1   
3  100004000.0  201.000000    BERKELEY           12            1      NaN   
4          NaN  203.000000    BERKELEY            Y            3        2   
5  100006000.0  207.000000    BERKELEY            Y          NaN        1   
6  100007000.0  191.428571  WASHINGTON          NaN            2   HURLEY   
7  100008000.0  213.000000     TREMONT            Y            1        1   
8  100009000.0  215.000000     TREMONT            Y           na        2   

  SQ_FT  
0  1000  
1    --  
2   850  
3   700  
4  1600  
5   800  
6   950  
7   800  
8  1800

In [29]:
len(data['NUM_BATH'])

9

In [32]:
for i in range(len(data['NUM_BATH'])):
    try:
        int(data['NUM_BATH'][i]) 
    except ValueError:
        data.loc[i, 'NUM_BATH'] = np.nan 
        
data

PID      ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH  \
0  100001000.0  104.000000      PUTNAM            Y            3        1   
1  100002000.0  197.000000   LEXINGTON            N            3      NaN   
2  100003000.0  191.428571   LEXINGTON            N          NaN        1   
3  100004000.0  201.000000    BERKELEY           12            1      NaN   
4          NaN  203.000000    BERKELEY            Y            3        2   
5  100006000.0  207.000000    BERKELEY            Y          NaN        1   
6  100007000.0  191.428571  WASHINGTON          NaN            2      NaN   
7  100008000.0  213.000000     TREMONT            Y            1        1   
8  100009000.0  215.000000     TREMONT            Y           na        2   

  SQ_FT  
0  1000  
1    --  
2   850  
3   700  
4  1600  
5   800  
6   950  
7   800  
8  1800

In [36]:
missing_values = ["n/a", "na", "--", "HURLEY"]
new_data = pd.read_csv('property_data.csv', na_values=missing_values)
new_data

PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH  \
0  100001000.0   104.0      PUTNAM            Y           3.0       1.0   
1  100002000.0   197.0   LEXINGTON            N           3.0       1.5   
2  100003000.0     NaN   LEXINGTON            N           NaN       1.0   
3  100004000.0   201.0    BERKELEY           12           1.0       NaN   
4          NaN   203.0    BERKELEY            Y           3.0       2.0   
5  100006000.0   207.0    BERKELEY            Y           NaN       1.0   
6  100007000.0     NaN  WASHINGTON          NaN           2.0       NaN   
7  100008000.0   213.0     TREMONT            Y           1.0       1.0   
8  100009000.0   215.0     TREMONT            Y           NaN       2.0   

    SQ_FT  
0  1000.0  
1     NaN  
2   850.0  
3   700.0  
4  1600.0  
5   800.0  
6   950.0  
7     NaN  
8  1800.0

In [34]:
new_data.dtypes

PID             float64
ST_NUM          float64
ST_NAME          object
OWN_OCCUPIED     object
NUM_BEDROOMS    float64
NUM_BATH        float64
SQ_FT           float64
dtype: object

## Assert

In [38]:
assert(data['ST_NUM'] is not np.nan)
assert(data['PID'] is not np.nan)

## Preprocessing

In [39]:
from sklearn import preprocessing

In [40]:
a_int = np.random.randint(-100, 100, 10)
a_int

array([ 60,  41,  37,  32, -38, -21, -85, -89, -75, -19])

In [41]:
a_str = ['foo', 'bar', 'baz', 'x', 'y', 'z', 'z', 'z']
a_str

['foo', 'bar', 'baz', 'x', 'y', 'z', 'z', 'z']

In [45]:
l_encoder = preprocessing.LabelEncoder()
l_encoder.fit_transform(a_str)

array([2, 0, 1, 3, 4, 5, 5, 5], dtype=int64)

In [46]:
print(l_encoder.transform(['foo']))
print(l_encoder.transform(['baz']))
print(l_encoder.transform(['bar']))

[2]
[1]
[0]


In [47]:
list(l_encoder.classes_)

['bar', 'baz', 'foo', 'x', 'y', 'z']

In [48]:
dict(zip(l_encoder.classes_, l_encoder.transform(l_encoder.classes_)))

{'bar': 0, 'baz': 1, 'foo': 2, 'x': 3, 'y': 4, 'z': 5}

In [55]:
l_encoder = preprocessing.LabelEncoder()
df = pd.DataFrame(data = {'col1': ['foo','bar','foo','bar'],
                          'col2': ['x', 'y', 'x', 'z'], 
                          'col3': [3000, 20, 3000, 400]})

In [56]:
df

col1 col2  col3
0  foo    x  3000
1  bar    y    20
2  foo    x  3000
3  bar    z   400

In [57]:
df['col1'] = l_encoder.fit_transform(df['col1'])
df

col1 col2  col3
0     1    x  3000
1     0    y    20
2     1    x  3000
3     0    z   400

In [59]:
df.apply(l_encoder.fit_transform)

col1  col2  col3
0     1     0     2
1     0     1     0
2     1     0     2
3     0     2     1

## One Hot Encoding

In [61]:
df = pd.DataFrame(data = {'col1': ['foo','bar','foo','bar'],
                          'col2': ['x', 'y', 'x', 'z'], 
                          'col3': [3000, 20, 3000, 400]})
df

col1 col2  col3
0  foo    x  3000
1  bar    y    20
2  foo    x  3000
3  bar    z   400

In [62]:
pd.get_dummies(df)

col3  col1_bar  col1_foo  col2_x  col2_y  col2_z
0  3000         0         1       1       0       0
1    20         1         0       0       1       0
2  3000         0         1       1       0       0
3   400         1         0       0       0       1

In [63]:
a_int

array([ 60,  41,  37,  32, -38, -21, -85, -89, -75, -19])

In [66]:
mm_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))

In [71]:
np.expand_dims(a_int, axis=1)

array([[ 60],
       [ 41],
       [ 37],
       [ 32],
       [-38],
       [-21],
       [-85],
       [-89],
       [-75],
       [-19]])

In [72]:
print(mm_scaler.fit_transform(np.expand_dims(a_int, axis=1)))

[[1.        ]
 [0.87248322]
 [0.84563758]
 [0.81208054]
 [0.34228188]
 [0.45637584]
 [0.02684564]
 [0.        ]
 [0.09395973]
 [0.46979866]]


In [73]:
mm_scaler.fit_transform(a_int.reshape(-1, 1))

array([[1.        ],
       [0.87248322],
       [0.84563758],
       [0.81208054],
       [0.34228188],
       [0.45637584],
       [0.02684564],
       [0.        ],
       [0.09395973],
       [0.46979866]])

In [74]:
mm_scaler = preprocessing.MinMaxScaler(feature_range=(0, 10))
mm_scaler.fit_transform(a_int.reshape(-1, 1))

array([[10.        ],
       [ 8.72483221],
       [ 8.45637584],
       [ 8.12080537],
       [ 3.42281879],
       [ 4.56375839],
       [ 0.26845638],
       [ 0.        ],
       [ 0.93959732],
       [ 4.69798658]])

In [75]:
X_train = np.array([[ 1., -1.,  2.],
                   [ 2.,  0.,  0.],
                   [ 0.,  1., -1.]])
X_scaled = preprocessing.scale(X_train)

X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [76]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [77]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [78]:
df

col1 col2  col3
0  foo    x  3000
1  bar    y    20
2  foo    x  3000
3  bar    z   400

In [79]:
numeric_df = df.apply(lambda x: np.log10(x) if np.issubdtype(x.dtype, np.number) else x)
numeric_df

col1 col2      col3
0  foo    x  3.477121
1  bar    y  1.301030
2  foo    x  3.477121
3  bar    z  2.602060

In [82]:
df[df.duplicated(keep=False)]

col1 col2  col3
0  foo    x  3000
2  foo    x  3000

In [83]:
df.duplicated().sum()

1

In [84]:
df[df.duplicated() == False]

col1 col2  col3
0  foo    x  3000
1  bar    y    20
3  bar    z   400

In [85]:
tmp = df[['col1', 'col2']]
tmp

col1 col2
0  foo    x
1  bar    y
2  foo    x
3  bar    z

In [86]:
tmp = df.drop(['col3'], axis=1)
tmp

col1 col2
0  foo    x
1  bar    y
2  foo    x
3  bar    z

In [87]:
tmp = df.drop(0, axis=0)
tmp

col1 col2  col3
1  bar    y    20
2  foo    x  3000
3  bar    z   400

In [89]:
arr = np.array([1, 7, 5, 4, 6, 3, 11, 17, 51, 14, 61, 23])
arr

array([ 1,  7,  5,  4,  6,  3, 11, 17, 51, 14, 61, 23])

In [90]:
pd.cut(arr, 4)

[(0.94, 16.0], (0.94, 16.0], (0.94, 16.0], (0.94, 16.0], (0.94, 16.0], ..., (16.0, 31.0], (46.0, 61.0], (0.94, 16.0], (46.0, 61.0], (16.0, 31.0]]
Length: 12
Categories (4, interval[float64, right]): [(0.94, 16.0] < (16.0, 31.0] < (31.0, 46.0] < (46.0, 61.0]]

In [91]:
pd.cut(np.array([1, 7, 5, 4, 6, 3]), 3, labels=["bad", "medium", "good"])

['bad', 'good', 'medium', 'medium', 'good', 'bad']
Categories (3, object): ['bad' < 'medium' < 'good']

In [92]:
df

col1 col2  col3
0  foo    x  3000
1  bar    y    20
2  foo    x  3000
3  bar    z   400

In [93]:
pd.cut(df['col3'], 3)

0    (2006.667, 3000.0]
1     (17.02, 1013.333]
2    (2006.667, 3000.0]
3     (17.02, 1013.333]
Name: col3, dtype: category
Categories (3, interval[float64, right]): [(17.02, 1013.333] < (1013.333, 2006.667] < (2006.667, 3000.0]]

In [94]:
pd.cut(df['col3'], 3, labels=False)

0    2
1    0
2    2
3    0
Name: col3, dtype: int64